package com.heretek.dorado_hd

import com.heretek.dorado_hd.data.model.Rating
import com.heretek.dorado_hd.sync.DeviceContentItem
import com.heretek.dorado_hd.sync.DeviceSnapshot
import com.heretek.dorado_hd.sync.SyncCategoryType
import com.heretek.dorado_hd.sync.SyncEngine
import com.heretek.dorado_hd.sync.SyncGroup
import com.heretek.dorado_hd.sync.SyncInput
import com.heretek.dorado_hd.sync.SyncMode
import com.heretek.dorado_hd.sync.SyncPhoto
import com.heretek.dorado_hd.sync.SyncPlan
import com.heretek.dorado_hd.sync.SyncPodcastEpisode
import com.heretek.dorado_hd.sync.SyncRuleSettings
import com.heretek.dorado_hd.sync.SyncTrack
import com.heretek.dorado_hd.sync.SyncVideo
import org.junit.Assert.assertEquals
import org.junit.Assert.assertFalse
import org.junit.Assert.assertNull
import org.junit.Assert.assertTrue
import org.junit.Test

/**
 * Golden tests for the Kotlin `SyncEngine` mirror. The expected plan strings
 * were generated by running the sibling Dorado desktop engine
 * (`Dorado.Application.Services.SyncEngine`) against the identical fixtures —
 * see the M8.1 harness. They lock in the exact ordering, keep/add/remove split
 * and capacity truncation.
 */
class SyncEngineTest {

    private fun g(n: Int) = "00000000-0000-0000-0000-%012d".format(n)

    private fun tracks() = listOf(
        SyncTrack(g(1), "Delta", "A", "Al", 1, "/t1", Rating.HEART),
        SyncTrack(g(2), "Alpha", "B", "Al", 2, "/t2", Rating.NONE),
        SyncTrack(g(3), "Charlie", "C", "Al", 3, "/t3", Rating.HEART),
        SyncTrack(g(4), "Bravo", "D", "Al", 4, "/t4", Rating.BROKEN),
        SyncTrack(g(5), "Echo", "E", "Al", 5, "/t5", Rating.HEART),
    )

    private fun episodes() = listOf(
        SyncPodcastEpisode(g(11), "Ep Old", "S1", 1577836800L, 1, "/p1", false),
        SyncPodcastEpisode(g(12), "Ep New", "S1", 1704067200L, 2, "/p2", false),
        SyncPodcastEpisode(g(13), "Ep Mid", "S1", 1640995200L, 3, "/p3", false),
        SyncPodcastEpisode(g(14), "Ep Played", "S1", 1735689600L, 4, "/p4", true),
    )

    private fun videos() = listOf(
        SyncVideo(g(21), "Vid A", "/v1", 100000, 1609459200L),
        SyncVideo(g(22), "Vid B", "/v2", 200000, 1672531200L),
    )

    private fun photos() = listOf(
        SyncPhoto(g(31), "Pho A", "/ph1", "F1", 50000, 1577836800L),
        SyncPhoto(g(32), "Pho B", "/ph2", "F1", 60000, 1640995200L),
        SyncPhoto(g(33), "Pho C", "/ph3", "F2", 70000, 1704067200L),
    )

    private fun input() = SyncInput(tracks(), videos(), photos(), episodes())

    private fun device() = DeviceSnapshot(
        totalCapacityBytes = 300000,
        systemBytes = 0,
        contents = listOf(
            DeviceContentItem(SyncCategoryType.MUSIC, g(1), "Delta", "/d1", 16000),
            DeviceContentItem(SyncCategoryType.MUSIC, g(99), "Stale Song", "/d9", 9000),
            DeviceContentItem(SyncCategoryType.PICTURES, g(98), "Stale Photo", "/d8", 7000),
            DeviceContentItem(SyncCategoryType.VIDEOS, g(21), "Vid A", "/d2", 100000),
            DeviceContentItem(SyncCategoryType.PODCASTS, g(97), "Stale Ep", "/d7", 5000),
        ),
    )

    private fun settings() = SyncRuleSettings(
        musicSyncRule = "Selected Favorites",
        podcastSyncRule = "3 Newest Episodes",
        videoSyncRule = "All Videos & Pictures",
        picturesSyncRule = "Newest 25 Items",
    )

    /** Canonical rendering that matches the desktop harness output exactly. */
    private fun canonical(plan: SyncPlan): String = buildString {
        append("group serial=${plan.deviceSerialNumber} guest=${plan.isGuestSession}")
        plan.items.forEach { item ->
            append('\n')
            append("ITEM ${item.action} ${item.category} ${item.entityId} bytes=${item.sizeBytes} ")
            append("title=${item.title} detail=${item.detail ?: ""}")
        }
        append('\n')
        append(
            "counts add=${plan.addCount} remove=${plan.removeCount} keep=${plan.keepCount} " +
                "addBytes=${plan.totalAddBytes} removeBytes=${plan.totalRemoveBytes}",
        )
    }

    private val goldenA = """
        group serial=SERIAL guest=false
        ITEM REMOVE MUSIC 00000000-0000-0000-0000-000000000099 bytes=9000 title=Stale Song detail=No longer in sync group
        ITEM REMOVE PICTURES 00000000-0000-0000-0000-000000000098 bytes=7000 title=Stale Photo detail=No longer in sync group
        ITEM REMOVE PODCASTS 00000000-0000-0000-0000-000000000097 bytes=5000 title=Stale Ep detail=No longer in sync group
        ITEM ADD MUSIC 00000000-0000-0000-0000-000000000003 bytes=48000 title=Charlie detail=C — Al
        ITEM KEEP MUSIC 00000000-0000-0000-0000-000000000001 bytes=16000 title=Delta detail=
        ITEM ADD MUSIC 00000000-0000-0000-0000-000000000005 bytes=80000 title=Echo detail=E — Al
        ITEM ADD PODCASTS 00000000-0000-0000-0000-000000000012 bytes=32000 title=Ep New detail=S1
        ITEM ADD PODCASTS 00000000-0000-0000-0000-000000000011 bytes=16000 title=Ep Old detail=S1
        ITEM KEEP VIDEOS 00000000-0000-0000-0000-000000000021 bytes=100000 title=Vid A detail=
        counts add=4 remove=3 keep=2 addBytes=176000 removeBytes=21000
    """.trimIndent()

    private val goldenB = """
        group serial=SERIAL guest=true
        ITEM ADD MUSIC 00000000-0000-0000-0000-000000000003 bytes=48000 title=Charlie detail=C — Al
        ITEM KEEP MUSIC 00000000-0000-0000-0000-000000000001 bytes=16000 title=Delta detail=
        ITEM ADD MUSIC 00000000-0000-0000-0000-000000000005 bytes=80000 title=Echo detail=E — Al
        ITEM ADD PODCASTS 00000000-0000-0000-0000-000000000012 bytes=32000 title=Ep New detail=S1
        ITEM KEEP VIDEOS 00000000-0000-0000-0000-000000000021 bytes=100000 title=Vid A detail=
        counts add=3 remove=0 keep=2 addBytes=160000 removeBytes=0
    """.trimIndent()

    private val goldenC = """
        group serial=SERIAL guest=false
        ITEM REMOVE PICTURES 00000000-0000-0000-0000-000000000098 bytes=7000 title=Stale Photo detail=No longer in sync group
        ITEM REMOVE PODCASTS 00000000-0000-0000-0000-000000000097 bytes=5000 title=Stale Ep detail=No longer in sync group
        ITEM ADD PODCASTS 00000000-0000-0000-0000-000000000012 bytes=32000 title=Ep New detail=S1
        ITEM ADD PODCASTS 00000000-0000-0000-0000-000000000013 bytes=48000 title=Ep Mid detail=S1
        ITEM ADD PODCASTS 00000000-0000-0000-0000-000000000011 bytes=16000 title=Ep Old detail=S1
        ITEM KEEP VIDEOS 00000000-0000-0000-0000-000000000021 bytes=100000 title=Vid A detail=
        ITEM ADD PICTURES 00000000-0000-0000-0000-000000000033 bytes=70000 title=Pho C detail=F2
        counts add=4 remove=2 keep=1 addBytes=166000 removeBytes=12000
    """.trimIndent()

    @Test
    fun `plan matches the desktop engine golden`() {
        val group = SyncEngine.buildDefaultGroup("SERIAL", settings())
        val plan = SyncEngine.buildPlan(group, input(), device())
        assertEquals(goldenA, canonical(plan))
    }

    @Test
    fun `guest session is add-only and matches the desktop golden`() {
        val group = SyncEngine.buildDefaultGroup("SERIAL", settings(), isGuestSession = true)
        val plan = SyncEngine.buildPlan(group, input(), device())
        assertEquals(goldenB, canonical(plan))
        assertEquals(0, plan.removeCount)
    }

    @Test
    fun `manual music is neither added nor removed and matches the desktop golden`() {
        val manual = settings().copy(musicSyncRule = "Manual")
        val group = SyncEngine.buildDefaultGroup("SERIAL", manual)
        val plan = SyncEngine.buildPlan(group, input(), device())
        assertEquals(goldenC, canonical(plan))
        assertTrue(plan.items.none { it.category == SyncCategoryType.MUSIC })
    }

    @Test
    fun `default group derives modes from rule strings like the desktop`() {
        val automatic = SyncEngine.buildDefaultGroup(
            "SERIAL",
            SyncRuleSettings(
                musicSyncRule = "All Music (Automatic Sync)",
                podcastSyncRule = "All Unplayed Episodes",
                videoSyncRule = "All Videos & Pictures",
                picturesSyncRule = "All Pictures",
            ),
        )
        assertEquals(SyncMode.AUTOMATIC, automatic.rule(SyncCategoryType.MUSIC).mode)
        assertFalse(automatic.rule(SyncCategoryType.MUSIC).preferFavorites)
        assertEquals(SyncMode.AUTOMATIC, automatic.rule(SyncCategoryType.PODCASTS).mode)
        assertNull(automatic.rule(SyncCategoryType.PODCASTS).newestCount)
        assertEquals(SyncMode.AUTOMATIC, automatic.rule(SyncCategoryType.VIDEOS).mode)
        assertEquals(SyncMode.AUTOMATIC, automatic.rule(SyncCategoryType.PICTURES).mode)

        val selected = SyncEngine.buildDefaultGroup(
            "SERIAL",
            SyncRuleSettings(
                musicSyncRule = "Selected Items",
                podcastSyncRule = "3 Newest Episodes",
                videoSyncRule = "Selected Items",
                picturesSyncRule = "5 Newest",
            ),
        )
        assertEquals(SyncMode.SELECTED_ITEMS, selected.rule(SyncCategoryType.MUSIC).mode)
        assertTrue(selected.rule(SyncCategoryType.MUSIC).preferFavorites)
        assertEquals(3, selected.rule(SyncCategoryType.PODCASTS).newestCount)
        assertEquals(SyncMode.SELECTED_ITEMS, selected.rule(SyncCategoryType.VIDEOS).mode)
        assertNull(selected.rule(SyncCategoryType.VIDEOS).newestCount)
        assertEquals(5, selected.rule(SyncCategoryType.PICTURES).newestCount)

        val manual = SyncEngine.buildDefaultGroup(
            "SERIAL",
            SyncRuleSettings(
                musicSyncRule = "Sync Manually",
                podcastSyncRule = "Sync Manually",
                videoSyncRule = "Nothing",
                picturesSyncRule = "Newest 25 Items",
            ),
        )
        assertEquals(SyncMode.MANUAL, manual.rule(SyncCategoryType.MUSIC).mode)
        assertEquals(SyncMode.MANUAL, manual.rule(SyncCategoryType.PODCASTS).mode)
        assertEquals(SyncMode.MANUAL, manual.rule(SyncCategoryType.VIDEOS).mode)
        assertEquals(SyncMode.MANUAL, manual.rule(SyncCategoryType.PICTURES).mode)
        assertNull(manual.rule(SyncCategoryType.PICTURES).newestCount)
    }

    @Test
    fun `parity details match the desktop`() {
        // Pictures inherit the video rule's mode.
        val inherited = SyncEngine.buildDefaultGroup(
            "SERIAL",
            SyncRuleSettings(videoSyncRule = "Selected Items", picturesSyncRule = "All Pictures"),
        )
        assertEquals(SyncMode.SELECTED_ITEMS, inherited.rule(SyncCategoryType.PICTURES).mode)

        // The count is the first digit run anywhere: "Newest 25 Items" → 25.
        val counted = SyncEngine.buildDefaultGroup(
            "SERIAL",
            SyncRuleSettings(videoSyncRule = "Selected Items", picturesSyncRule = "Newest 25 Items"),
        )
        assertEquals(25, counted.rule(SyncCategoryType.PICTURES).newestCount)

        // REMOVE items carry the device item's size, so stale content frees
        // capacity for the adds that follow.
        val plan = SyncEngine.buildPlan(
            SyncEngine.buildDefaultGroup("SERIAL", settings()),
            input(),
            device(),
        )
        assertTrue(plan.removeCount > 0)
        assertEquals(21000L, plan.totalRemoveBytes)
    }

    private fun SyncGroup.rule(category: SyncCategoryType) =
        categories.first { it.category == category }
}
