<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>sync_golden</AssemblyName>
    <RootNamespace>SyncGolden</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../../dorado/src/Dorado.Application/Dorado.Application.csproj" />
  </ItemGroup>

</Project>
