#!/usr/bin/env python3
"""Dorado-HD .zcp corpus inventory generator.

Reads the ZuneRedux `zune-hd-apps` archive (review/Zune HD Apps), parses the
NX container headers and plaintext manifests, and writes docs/zcp-inventory.md
plus a stdout summary. Read-only with respect to the .zcp files.

NX container layout (empirically derived, see docs/zcp-inventory.md):
  0x000  NX header (u32 fields; magic 0x584E07D3 "…NX" at 0x30)
  0x1F0  Authenticode PKCS#7 SignedData (hdr[4]=offset, hdr[7]=length)
  0x2800 record manifest: EXEC (lang 0x0409, GUID, exe, platform) / TITL (UTF-16)
  after  encrypted payload: AES-ECB (16-byte aligned identical ciphertext
         blocks, unique block tail per package) — marketplace DRM, unrecoverable.
"""
import os
import re
import struct
import sys
from collections import Counter

APP_DIR = os.path.join(os.path.dirname(__file__), "..", "review", "Zune HD Apps")
OUT = os.path.join(os.path.dirname(__file__), "..", "docs", "zcp-inventory.md")


def utf16_at(buf: bytes, off: int, maxn: int = 600) -> str:
    out = bytearray()
    i = off
    while i + 1 < len(buf) and maxn > 0:
        v = buf[i] | (buf[i + 1] << 8)
        if v == 0:
            break
        if not (32 <= v < 0x2500):
            break
        out += buf[i:i + 2]
        i += 2
        maxn -= 1
    return out.decode("utf-16-le", "ignore")


def parse_package(path: str):
    data = open(path, "rb").read()
    hdr = struct.unpack_from("<8I", data, 0)
    sig_off, sig_len = hdr[4], hdr[7]
    assert data[50:52] == b"NX", "NX magic missing"
    assert data[sig_off:sig_off + 2] == b"\x30\x82", "PKCS#7 SEQUENCE missing"
    seg = data[0x2800: min(0x8000, len(data))]
    m = re.search(rb"EXEC.{4}([0-9a-f]{32})\x00([ -~]+?)\x00", seg, re.S)
    guid = m.group(1).decode() if m else ""
    exe = m.group(2).decode() if m else ""
    mv = re.search(rb"(Zune\.v[0-9.]+)", seg)
    platform = mv.group(1).decode() if mv else ""
    title = desc = ""
    mt = re.search(rb"TITL", seg)
    if mt:
        title = utf16_at(seg, mt.end() + 4)
        scan = seg[mt.end():]
        best = b""
        for m2 in re.finditer(rb"(?:[\x20-\x7e]\x00){8,}", scan):
            if len(m2.group()) > len(best):
                best = m2.group()
        desc = best.decode("utf-16-le", "ignore")
    # ECB signature: unique 16-byte block repeated at the tail
    blk = data[-16:]
    n = len(data)
    tail = 0
    while tail * 16 < n // 2 and data[n - (tail + 1) * 16: n - tail * 16] == blk:
        tail += 1
    return {
        "file": os.path.basename(path), "guid": guid, "exe": exe,
        "platform": platform, "title": title, "desc": desc,
        "size": len(data), "ecb_tail": blk.hex(), "ecb_tail_blocks": tail,
    }


def main() -> int:
    rows = []
    for fn in sorted(os.listdir(APP_DIR)):
        if fn.endswith(".zcp"):
            rows.append(parse_package(os.path.join(APP_DIR, fn)))
    lines = [
        "# Zune HD App Package (.zcp) Inventory",
        "",
        "Generated by `tools/zcp_inventory.py` from the ZuneRedux `zune-hd-apps`",
        "archive (62 installable marketplace packages). Design reference only —",
        "per canon §8 and NOTICE, no Microsoft binary or asset is bundled or",
        "shipped by Dorado-HD.",
        "",
        "## Container format (NX)",
        "",
        "| Region | Offset | Contents |",
        "|---|---|---|",
        "| NX header | `0x000`–`0x1F0` | u32 fields; magic `4e 58` (\"NX\") at `0x32` behind a small version word (`07 d2`/`07 d3`); SHA-1 + GUID fingerprints |",
        "| Authenticode signature | `0x1F0` (hdr[4]), len hdr[7] (≈0x1DE0–0x1DEF) | PKCS#7 SignedData: `Microsoft Zune Publisher` ← `Microsoft Home Entertainment PCA`, MS Time-Stamp PCA countersignature |",
        "| Record manifest | `0x2800…` | `EXEC` records: lang `0x0409`, package GUID, `<App>.exe`, platform `Zune.v3.1`; `TITL`: UTF-16LE title + description |",
        "| Payload | after manifest | AES-ECB encrypted (16-byte-aligned identical ciphertext blocks; unique block tail per package). Marketplace DRM keys were device-delivered and are unrecoverable. |",
        "",
        "**Verdict:** binaries and XNA content are not extractable. The manifest",
        "(facts only) is inventoried below; each app is re-implemented as",
        "behavior, never extracted or bundled.",
        "",
        "## Packages",
        "",
        "| # | App | Executable | Package GUID | Size | Description |",
        "|---|---|---|---|---|---|",
    ]
    for i, r in enumerate(rows, 1):
        desc = r["desc"].replace("|", "/").strip()
        lines.append(
            f"| {i} | {r['title']} | {r['exe']} | `{r['guid']}` | {r['size'] // 1024} KB | {desc} |"
        )
    lines += [
        "",
        "All packages target platform `Zune.v3.1` (XNA Game Studio 3.1, Zune",
        "distribution) and are signed by Microsoft Zune Publisher. Two packages",
        "share GUID `97cfdcae937f46d999651163741d1f5x` (ColorSpill, Reversi,",
        "Vine Climb) — upstream packaging quirk.",
        "",
    ]
    with open(OUT, "w") as f:
        f.write("\n".join(lines))
    print(f"wrote {OUT} ({len(rows)} packages)")
    for r in rows:
        print(f"  {r['title']:<32} {r['exe']:<38} {r['guid']}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
